# Generated by Django 6.0.6 on 2026-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salle",
            name="disponible",
        ),
        migrations.AddField(
            model_name="jury",
            name="present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="soutenance",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admis", "Admis"),
                    ("corrections", "Admis avec corrections"),
                    ("ajourne", "Ajourné"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soutenance",
            name="note",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="soutenance",
            name="observations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="memoire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("soumis", "Soumis"),
                    ("valide", "Validé"),
                    ("rejete", "Rejeté"),
                ],
                default="soumis",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="statut",
            field=models.CharField(
                choices=[("ouverte", "Ouverte"), ("fermee", "Fermée")],
                default="ouverte",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="soutenance",
            name="statut",
            field=models.CharField(
                choices=[
                    ("planifiee", "Planifiée"),
                    ("validee", "Validée"),
                    ("rejetee", "Rejetée"),
                    ("terminee", "Terminée"),
                ],
                default="planifiee",
                max_length=20,
            ),
        ),
    ]
